### ISSUE TITLE
attachment_preview: ViewerJS empty document

### ISSUE THREAD

**Issue by mgielissen** [OCA/knowledge#67] opened 2015-08-31 19:48 UTC
ViewerJS window doesn't show any pdf attachment.

Java console log shows: 
viewerjs_tweaks.js:30 Uncaught TypeError: Cannot set property 'title' of

**Comment by StefanRijnhart** [comment] 2015-09-04 09:39
For your info, @hbrunn

**Comment by whoople** [comment] 2015-09-12 14:26
Same Issue :+1: 
ViewerJS window doesn't show any pdf attachment.
Thanks for help

**Comment by sysadminmatmoz** [comment] 2015-09-12 17:59
It works well on fresh databases, the problem seems connected with the existing web/js/web.assets... when updating from the previous version of jsviewer.

**Comment by ezerouali** [comment] 2015-09-16 18:49
Seem like error is generated within the javascript file:
viewerjs_tweaks.js

The error is due to a missing argument:
Uncaught TypeError: Cannot set property 'title' of undefined

The tweak may be causing the error:
    
    <script src="../../src/js/viewerjs_tweaks.js" type="text/javascript" charset="utf-8"></script>

Have you found the solution ?

I'll keep searching myself... just in case

**Comment by mgielissen** [comment] 2015-09-16 19:30
Nope

**Comment by sysadminmatmoz** [comment] 2015-09-17 04:15
Did you try it on a fresh DB? I can't reproduce your error on a fresh DB. On an existing DB update on the other hand, I just deleted the /web/js/web.assets.backend attachments relative to attachment_preview, cleaned the nginx cache, made a restart and update --all in I managed to make it work there too (but it was time consuming).

**Comment by mgielissen** [comment] 2015-10-06 12:55
I tried it on a fresh DB, stil the same problem.

**Comment by nedaszilinskas** [comment] 2015-10-14 11:23
I have exactly the same issue, on clean DB also.

FIY: works on commit 0a42df9a1807fa3439206e79ff4b22e66a919601

**Comment by sysadminmatmoz** [comment] 2015-10-14 12:54
That's related probably to your cache (reverse proxy cache) if you host a fresh DB on the same address where you had a DB with the old module... cleaning the odoo server's proxy cache (and browser cache) at least worked for me

**Comment by hbrunn** [comment] 2015-11-17 20:12
so the root of the issue is odoo not passing the correct mimetype, which usually is a misconfiguration of the database. #79 fixes this.

**Comment by mgielissen** [comment] 2015-11-19 12:08
@hbrunn Your latest commit solves the problem with a existing database. Many thanks!

**Comment by StefanRijnhart** [comment] 2015-11-19 12:58
https://github.com/OCA/knowledge/issues/79 is not merged yet. I'm reopening this issue until then. @mgielissen, could you post a thumbs-up on the PR as a review?

**Closed as completed** 2015-12-14 10:21 UTC
Labels: bug
