### ISSUE TITLE
[8.0] document_page error mass mailing

### ISSUE THREAD

**Issue by ccarly** [OCA/knowledge#78] opened 2015-11-10 17:01 UTC
When access menu Marketin / Mass Mailing

```
192.168.254.209 - - [2015-11-10 16:44:40] "POST /web/dataset/call_kw/mail.mass_mailing/fields_view_get HTTP/1.1" 200 5347 0.039534
192.168.254.209 - - [2015-11-10 16:44:40] "POST /web/dataset/call_kw/ir.filters/get_filters HTTP/1.1" 200 286 0.009001
2015-11-10 16:44:40,974 16727 WARNING mydb openerp.addons.document_page.document_page: Trying to access attribute _mail_mass_mailing on document_page_history
2015-11-10 16:44:40,974 16727 WARNING mydb openerp.addons.document_page.document_page: Trying to access attribute _mail_mass_mailing on document_page_history
2015-11-10 16:44:40,974 16727 WARNING mydb openerp.addons.document_page.document_page: Trying to access attribute _mail_mass_mailing on document_page_history
2015-11-10 16:44:40,978 16727 ERROR mydb openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/data/home/openerp/bin/8.0/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/home/openerp/bin/8.0/openerp/http.py", line 588, in dispatch
    return self._json_response(result)
  File "/data/home/openerp/bin/8.0/openerp/http.py", line 526, in _json_response
    body = simplejson.dumps(response)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 354, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/dist-packages/simplejson/encoder.py", line 262, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/dist-packages/simplejson/encoder.py", line 340, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/dist-packages/simplejson/encoder.py", line 239, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <function <lambda> at 0x7fb228106b18> is not JSON serializable
192.168.254.209 - - [2015-11-10 16:44:40] "POST /web/dataset/call_kw/mail.mass_mailing/fields_get HTTP/1.1" 200 1587 0.012133
```

**Comment by neotekpc** [comment] 2016-01-18 17:54
Believe this error only shows up with update to python package python-2.7.5-34.el7.x86_64.  With package python-2.7.5-18.el7_1.1.x86_64 the error is not present.  This is of course rpm based Linux installs CentOS, RH.

**Comment by max3903** [comment] 2016-01-18 17:57
Duplicate of #54

**Closed as completed by max3903** 2016-01-18 17:57 UTC
Labels: bug
