### ISSUE TITLE
odoo 8.0 830fc89 document_page IndexError: list index out of range when open Page

### ISSUE THREAD

**Issue by alanljj** [OCA/knowledge#96] opened 2016-07-20 04:19 UTC
my odoo version: 8.0 830fc89
I use document_page more than 3 months, create many page and category without any error. From yesterday, when I click the menu of Pages everytime, the error pop out:

Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 543, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 580, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/openerp/http.py", line 313, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/openerp/http.py", line 809, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/openerp/http.py", line 409, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 884, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/opt/odoo/addons/web/controllers/main.py", line 905, in do_search_read
    request.context)
  File "/opt/odoo/openerp/http.py", line 914, in proxy
    result = meth(cr, request.uid, _args, *_kw)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 5198, in search_read
    result = self.read(cr, uid, record_ids, fields, context=read_ctx)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 3144, in read
    result = BaseModel.read(records, fields, load=load)
  File "/opt/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 3190, in read
    values[name] = field.convert_to_read(record[name], use_name_get)
  File "/opt/odoo/openerp/fields.py", line 1597, in convert_to_read
    return value_sudo.name_get()[0]
IndexError: list index out of range

I didn't find same error message online, would you please help to find the reason?

**Comment by max3903** [comment] 2016-07-20 14:46
@alanljj Please read https://odoo-community.org/page/bugs and especially step 3.

Thanks

**Comment by alanljj** [comment] 2016-07-21 02:04
@max3903 thank you for your guidence, I've updated my report, please help check the problem.

**Comment by max3903** [comment] 2016-07-21 14:59
@alanljj What did you do before yesterday? Did you change anything in your environment?

**Comment by alanljj** [comment] 2016-07-25 10:12
@max3903 I didn't update any code for system, just as normal add some pages. Then one of my colleague found this error.

**Comment by max3903** [comment] 2016-07-25 14:51
@alanljj Can you check in your database the name of the last created page? Maybe a special character. It's pretty difficult for me to fix the issue if I can't reproduce it. What did your colleague do before getting the error? Did he create or modify a page? What is the name of the page? What are the modifications?

**Comment by alanljj** [comment] 2016-08-02 04:19
@max3903 I found the final page called "NAP for ABAP", I  deleted it and recreate the same page, the error disapeared, I just use the same content. here is full html code for this page:

<table width="100%" border="1" cellspacing="0" cellpadding="10">
  <tbody>
    <tr bgcolor="#887ddd">
      <td align="center"><p style="align-content:center; font-size:18px; font-style:oblique; color:#ffffff"><strong>Geeker Need Analysis Profile</strong></p></td>
    </tr>
    <tr bgcolor="#d1d2d4">
      <td>
    <p>Why open this position?</p></td></tr>
    
    <tr><td align="left">
<p>&nbsp;内部供应链方面的产品开发</p> 
    </td>
    </tr>
    
    <tr bgcolor="#d1d2d4"><td align="left">
<p>Which skills is most important?</p>
    </td>
    </tr>
    
        <tr><td align="left">
<p>&nbsp;SAP开发语言ABAP</p>
    </td>
    </tr>
    
        <tr bgcolor="#d1d2d4"><td align="left">
<p>Company Introduction and Org chart?</p>
    </td>
    </tr>
    
        <tr><td align="left">
<p>&nbsp;团队</p>
    </td>
    </tr>
    
        <tr bgcolor="#d1d2d4"><td align="left">
<p>Interview related</p>
    </td>
    </tr>
    
        <tr><td align="left">
<p>&nbsp;第一轮技术面试：2个候选人都被同时问到程序性能调优和接口开发相关的问题。</p>
    </td>
    </tr>
    
        <tr bgcolor="#d1d2d4"><td align="left">
<p>Salary Package?</p>
    </td>
    </tr>
    
    <tr><td align="left"><p>&nbsp;不要高于40万</p></td>
    </tr>
    <tr bgcolor="#887ddd">
      <td><p style="font-size:11px; color:#ffffff">请和客户保持密切沟通，以便更好的理解客户的需求。Please keep closed communication with client to complete NAP.</p></td>
    </tr>
  </tbody>
</table>

**Comment by max3903** [comment] 2016-08-02 14:23
@alanljj Shall we close this issue? I understand that the same page name and content works now, right?

**Closed as completed** 2016-08-10 13:53 UTC
Labels: invalid, work in progress
